# This is a basic workflow to help you get started with Actions

name: geopop Web CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean old docker images, networks,...
      run: /usr/bin/docker system prune -f

    - name: Run build and deploy
      run: /usr/local/bin/docker-compose build && /usr/local/bin/docker-compose up -d

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: shguswnsd@gmail.com
        password: !Dlf1773144

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: shguswnsd@gmail.com/reg.dev.opnd.io:latest